<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Person.DataAccess.Context\Person.DataAccess.Context.csproj" />
      <ProjectReference Include="..\Person.Domain.Interfaces\Person.Domain.Interfaces.csproj" />
    </ItemGroup>

</Project>
