<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RuntimeIdentifier>linux-x64</RuntimeIdentifier>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.0"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0"/>
        <PackageReference Include="MockQueryable.Moq" Version="8.0.0" />
        <PackageReference Include="Moq.EntityFrameworkCore" Version="9.0.0.5" />
        <PackageReference Include="xunit" Version="2.5.3"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Person.DataAccess.Context\Person.DataAccess.Context.csproj" />
      <ProjectReference Include="..\Person.DataAccess.PersonModels\Person.DataAccess.PersonModels.csproj" />
      <ProjectReference Include="..\Person.DataAccess.Repositories\Person.DataAccess.Repositories.csproj" />
      <ProjectReference Include="..\Person.Domain.Interfaces\Person.Domain.Interfaces.csproj" />
      <ProjectReference Include="..\Person.Domain.PersonModels\Person.Domain.PersonModels.csproj" />
    </ItemGroup>

</Project>
